### PR TITLE
Initial CI

### PR DESCRIPTION
**Pull request by magmaus3**
This PR contains github actions workflows that can be used for building the game.

Currently 4 workflows are provided:
- `build-android.yml`
- `build-linux.yml`
- `build-windows.yml`
- `build.yml` - the workflow that triggers the other ones, for example by pushing.

The first 3 workflows are [reusable](https://docs.github.com/en/actions/using-workflows/reusing-workflows), so it might be possible to set up builds for release targets with minimal effort. They can also be used separately.

The builds have game resources bundled, which are downloaded automatically.

### CODE REVIEW

**Comment by iAndyHD3** [comment]
can you avoid bundling assets, this was fine for testing but not on the actual repo

**Comment by magmaus3** [comment]
> can you avoid bundling assets, this was fine for testing but not on the actual repo

Sure, but the android builds might stop working, since the assets are bundled with the apk itself.

**Comment by iAndyHD3** [comment]
indeed the android version wouldn't work, in the future ill add something that copies the assets so dont bundle them. 

what you can do is bundle the resources from the repo (contains a custom folder keeps changing from time to time)

**Comment by magmaus3** [comment]
done

**Pull request merged**
